# This file is covered by the LICENSE file in the root of this project.
name: "kitti"
labels:
0:	'Unlabeled'
1:	'Building'
2: 'Fence'
3: 'Other'
4: 'Pedestrian'	
5:	'Pole'
6:	'RoadLine'
7:	'Road'	
8:	'SideWalk'
9:	'Vegetation'	
10:	'Vehicles'
11:  'wall'
12:	'TrafficSign'	
13:	'Sky'	
14:	'Ground'
15:	'Bridge'
16:	'RailTrack'
17:	'GuardRail'
18:	'TrafficLight'
19:	'Static'	
20:	'Dynamic'	
21:	'Water'	
22:	'Terrain'	
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.043
  1: 0.043
  2: 0.043
  3: 0.043
  4: 0.043
  5: 0.043
  6: 0.043
  7: 0.043
  8: 0.043
  9: 0.043
  10: 0.043
  11: 0.043
  12: 0.043
  13: 0.043
  14: 0.043
  15: 0.043
  16: 0.043
  17: 0.043
  18: 0.043
  19: 0.043
  20: 0.043
  21: 0.043
  22: 0.043
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent

new_labels:
  0: 'road'
  1: 'vegetation'
  2: 'terrain'
  3: 'vehicle'
  # 5: 'truck'
  # 6: 'bus'
  4: 'manmade'
  255: 'unlabel'
learning_map:
  0: 5 #Unlabeled
  1: 4 #Building
  2: 5 #Fence
  3: 5 #Other
  4: 5 #####Pedestrian
  5: 5 #Pole
  6: 5 #RoadLine
  7: 0 #Road
  8: 5 #SideWalk
  9: 1 #Vegetation
  10: 3 #Vehicles
  11: 4 #wall
  12: 5 #TrafficSign
  13: 5 #Sky
  14: 0 #Ground
  15: 4 #Bridge
  16: 5 #RailTrack
  17: 5 #GuardRail
  18: 5 #TrafficLight
  19: 5 #Static
  20: 5 #Dynamic
  21: 5 #Water
  22: 2 #Terrain
learning_map_inv: # inverse of previous map
  0: 7     # road
  # 1: 26     # sidewalk
  1: 9     # vegetation
  2: 22     # terrain
  3: 10      # vehicle
  4: 1     # manmade
  5: 0      # noise


  # 0: 0      # "unlabeled", and others ignored
  # 1: 10     # "car"
  # 2: 11     # "bicycle"
  # 3: 15     # "motorcycle"
  # 4: 18     # "truck"
  # 5: 20     # "other-vehicle"
  
  # 6: 30     # "person"
  # 7: 31     # "bicyclist"
  # 8: 32     # "motorcyclist"
  # 9: 40     # "road"
  # 10: 44    # "parking"
  # 11: 48    # "sidewalk"
  # 12: 49    # "other-ground"
  # 13: 50    # "building"
  # 14: 51    # "fence"
  # 15: 70    # "vegetation"
  # 16: 71    # "trunk"
  # 17: 72    # "terrain"
  # 18: 80    # "pole"
  # 19: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"
  17: False    # "terrain"
  18: False    # "pole"
  19: False    # "traffic-sign"
split: # sequence numbers
  train:
    - 20
    - 21
    - 22
    - 23
    - 24
  valid:
    - 15
  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21

dataset:
      train_path: '/SSD_DISK/users/kuangshaochen/semantickitti_nerf_city'
      train_scale: 50
      train_scene: ['frames1','frames2',]
      valid_path: '/SSD_DISK/users/kuangshaochen/nus_data'

nerf_use_mapping_real:
  0: 5 # 'noise'
  1: 5 # 'animal'
  2: 5 # 'human.pedestrian.adult'
  3: 5 # 'human.pedestrian.child'
  4: 5 # 'human.pedestrian.construction_worker'
  5: 5 # 'human.pedestrian.personal_mobility'
  6: 5 # 'human.pedestrian.police_officer'
  7: 5 # 'human.pedestrian.stroller'
  8: 5 # 'human.pedestrian.wheelchair'
  9: 5 # 'movable_object.barrier'
  10: 5 # 'movable_object.debris'
  11: 5 # 'movable_object.pushable_pullable'
  12: 5 # 'movable_object.trafficcone'
  13: 5 # 'movable_object.trafficcone'
  14: 5 # 'vehicle.bicycle'
  15: 3 # 'vehicle.bus.bendy'
  16: 3 # 'vehicle.bus.rigid'
  17: 3 # 'vehicle.bus.rigid'
  18: 5 # 'vehicle.construction'
  19: 5 # 'vehicle.emergency.ambulance'
  20: 5 # 'vehicle.emergency.police'
  21: 5 # 'vehicle.motorcycle'
  22: 5 # 'vehicle.trailer'
  23: 3 # 'vehicle.truck'
  24: 0 # 'flat.driveable_surface'
  25: 5 # 'flat.other'
  26: 5 # 'flat.sidewalk'
  27: 2 # 'flat.terrain'
  28: 4 # 'static.manmade'
  29: 5 # 'static.other'
  30: 1 # 'static.vegetation'
  31: 5 # 'vehicle.ego'