labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
city_labels:
  0: 'road' # driveable_surface
  1: 'sidewalk' # sidewalk
  2: 'building' # manmade
  3: 'wall' # manmade
  4: 'fence' # manmade
  5: 'pole' # manmade
  6: 'traffic-light' # manmade
  7: 'traffic-sign' # manmade
  8: 'vegetation'
  9: 'terrain'
  10: 'sky' # None
  11: 'person'
  12: 'rider'
  13: 'car'
  14: 'truck'
  15: 'bus'
  16: 'train'
  17: 'motorcycle'
  18: 'bicycle'
new_labels:
  0: 'road'
  1: 'sidewalk'
  # 2: 'building'
  # 3: 'wall'
  # 4: 'fence'
  # 5: 'pole'
  # 6: 'traffic-light'
  # 7: 'traffic-sign'
  2: 'vegetation'
  3: 'terrain'
  # 4: 'person'
  # 5: 'rider'
  4: 'car'
  5: 'truck'
  6: 'bus'
  # 7: 'train'
  # 10: 'motorcycle'
  # 11: 'bicycle'
  8: 'manmade'
  255: 'unlabel'

learning_map:
  0: 255
  1: 255
  2: 255
  3: 255
  4: 255
  5: 255
  6: 255
  7: 255
  8: 255
  9: 255
  10: 255
  11: 255
  12: 255
  13: 255
  14: 255
  15: 6
  16: 6
  17: 4
  18: 255
  19: 255
  20: 255
  21: 255
  22: 7
  23: 5
  24: 0
  25: 255
  26: 1
  27: 3
  28: 8
  29: 255
  30: 2
  31: 255
  # 1 : 0
  # 5 : 0
  # 7 : 0
  # 8 : 0
  # 10 : 0
  # 11 : 0
  # 13 : 0
  # 19 : 0
  # 20 : 0
  # 0 : 0
  # 29 : 0
  # 31 : 0
  # 9 : 1
  # 14 : 2
  # 15 : 3
  # 16 : 3
  # 17 : 4
  # 18 : 5
  # 21 : 6
  # 2 : 7
  # 3 : 7
  # 4 : 7
  # 6 : 7
  # 12 : 8
  # 22 : 9
  # 23 : 10
  # 24 : 11
  # 25 : 12
  # 26 : 13
  # 27 : 14
  # 28 : 15
  # 30 : 16

split: # sequence numbers
  train:
    - 0
 
  valid:
    - 15
  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
  ## this actually is the label from semantic kitti
  # learning_ignore: # Ignore classes
  # 0: True      # "unlabeled", and others ignored
  # 1: False     # "car"
  # 2: False     # "bicycle"
  # 3: False     # "motorcycle"
  # 4: False     # "truck"
  # 5: False     # "other-vehicle"
  # 6: False     # "person"
  # 7: False     # "bicyclist"
  # 8: False     # "motorcyclist"
  # 9: False     # "road"
  # 10: False    # "parking"
  # 11: False    # "sidewalk"
  # 12: False    # "other-ground"
  # 13: False    # "building"
  # 14: False    # "fence"
  # 15: False    # "vegetation"
  # 16: False    # "trunk"
  # 17: False    # "terrain"
  # 18: False    # "pole"
  # 19: False    # "traffic-sign"