# Config format schema number
format_version: 4

#----------------------#
#文件描述 相较于 v1 v2config 修改在 label_v2 增加 split 的数据量上 10k
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 8
  out_fea_dim: 256
  num_class: 8
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_nus32_lidar"
  pc_dataset_type_val: "SemKITTI_nus32_lidar"
  ignore_label: 255
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/nus32_label_v2.yaml"
  label_mapping_val: "./config/label_mapping/nus32_label_v2.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "../nus_data/sequences"
  imageset: "train"
  return_ref: False
  batch_size: 4
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "../nus_data/sequences"
  imageset: "val"
  return_ref: False
  batch_size: 4
  shuffle: False
  num_workers: 4


###################
## Train params
train_params:
  exp_path: "./exp/nus32_v2"
  model_load_path: "./nus32_v2.pt"
  model_save_path: "./nus32_v2.pt"
  checkpoint_every_n_steps: 10000
  max_num_epochs: 40
  eval_every_n_steps: 2000
  learning_rate: 0.001


# Validation per class iou: 
# road : 92.80%
# sidewalk : 56.31%
# vegetation : 81.23%
# terrain : 62.40%
# car : 80.56%
# truck : 59.90%
# bus : 47.00%
# manmade : 83.53%
# Current val miou is 70.466 while the best val miou is 70.903
# Current val loss is 0.840
# epoch 97 iter   235, loss: 0.369